name: CI Check

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.x
          - 14.x
          - 16.x
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.3.2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2.3.4
      - run: npm ci
      - run: npm run lint
      - run: npm run test
        env:
          CI: true
