name: Editor Config

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Editor Config Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check file formatting against EditorConfig
        uses: editorconfig-checker/action-editorconfig-checker@v1.0.0
